### ISSUE TITLE
I created a fork with fixes

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/zwave-adapter#136]
I've created a version of the zwave-adapter that makes a few small changes so that it works on Candle / Gateway 2.0.
- It can detect Zigbee USB sticks and avoid connecting to them, something the current addon does, and disrupts Zigbee2MQTT.
- It removed the visibility check
- It changes "on/off" property names to "state" to be better compatible with voice control
- It updates to the latest version of Open Zwave

You can find it here:
https://github.com/createcandle/candle-zwave-adapter

**Comment by benfrancis** [comment]
No action needed.
